### ISSUE TITLE
API returns garbage "zkb" values for some NPC kills

### ISSUE THREAD

**Issue by Tharre** [EVE-KILL/zKillboard#318]
Hi, there seems to be a bug in the API that causes the "zkb" key to be replaced by this garbage: ```"_stringValue": "\n        \n        \n        \n      "```

There is also a useless key that shouldn't be there: ```"victim": ""```

Example: https://beta.eve-kill.net/api/kills/killID/46581118/no-items/

There are actually a lot of kills of this type, and in every single one that I've seen so far the attackers were exclusively NPCs.

**Comment by karbowiak** [comment]
the _stringValue is a byproduct of the xml to json conversion, that you can ignore.
As for the useless keys, they're there because the parser sets them regardless of if they actually contain data or not.

And yes, you're right, it's exclusively NPCs that have no data in those places.
Just ignore that data, and use the data you need :)

**Comment by Tharre** [comment]
Wait, what? The data must be available on the server, after all the website shows things like the totalValue without any issues. So this must be a bug, right? Any reasons for not fixing it? Don't really want to go through all those kills and parse the data from the website directly.

**Comment by karbowiak** [comment]
oh, hah, you were talking about the missing zkb: field.. doh

Yes, it's most likely a bug that they're not there.

I'll get it fixed! :)

**Comment by karbowiak** [comment]
Should be fixed now with commit  7e9e9f4aaeda02aa43a88b04d53a020b1444d019 :)

**Comment by Tharre** [comment]
Thank you very much for this fix.
